services:
  odysseia-protect:
    build:
      context: .
      target: base
    container_name: odysseia-protect
    restart: unless-stopped
    env_file:
      - .env
    command: ["python", "main.py"]
    volumes:
      - ./data:/app/data
    networks:
      - bot-bridge

  odysseia-protect-migrate:
    build:
      context: .
      target: dev
    container_name: odysseia-protect-migrate
    profiles:
      - migrate
    env_file:
      - .env
    command: ["python", "migrate.py"]
    volumes:
      - ./data:/app/data

networks:
  bot-bridge:
    external: true
    name: ${BOT_BRIDGE_NETWORK:-Odysseia-BOT}
