"""add quick_mode_enabled to threads table

Revision ID: 5e6f70913e2c
Revises: 6d5b5b88983b
Create Date: 2025-12-12 14:50:32.828781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e6f70913e2c"
down_revision: Union[str, Sequence[str], None] = "6d5b5b88983b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads") as batch_op:
        batch_op.add_column(
            sa.Column(
                "quick_mode_enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads") as batch_op:
        batch_op.drop_column("quick_mode_enabled")
    # ### end Alembic commands ###
