"""add reaction_emoji to threads

Revision ID: f7b4c3d9a1e0
Revises: b1a7a6c0e8d5
Create Date: 2024-05-18 13:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7b4c3d9a1e0"
down_revision: Union[str, None] = "b1a7a6c0e8d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("threads", schema=None) as batch_op:
    #     batch_op.add_column(
    #         sa.Column("reaction_emoji", sa.String(length=50), nullable=True)
    #     )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("threads", schema=None) as batch_op:
    #     batch_op.drop_column("reaction_emoji")
    pass
    # ### end Alembic commands ###
