"""add reaction_required to threads

Revision ID: b1a7a6c0e8d5
Revises: 939f3c162e83
Create Date: 2024-05-18 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1a7a6c0e8d5"
down_revision: Union[str, None] = "939f3c162e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reaction_required",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_column("reaction_required")
    # ### end Alembic commands ###
